docker run -d -p 80:80 -p 443:443 \
  -e ASPNETCORE_URLS="https://+;http://+" \
  -e ASPNETCORE_HTTPS_PORT=443 \
  -e ASPNETCORE_Kestrel__Certificates__Default__Password="fcra@123" \
  -e ASPNETCORE_Kestrel__Certificates__Default__Path="/app/example.pfx" \
  -e MetadataAddress="https://login.microsoftonline.com/ba04dd9d-19c9-423e-85c1-63bc63f9ff4c/federationmetadata/2007-06/federationmetadata.xml?appid=d58bfe58-9cf7-4e27-84ec-39fd728ab156" \
  -e username="sa" \
  -e password="fcra@123" \
  -e host="3.111.217.219" \
  -e port="" \
  -e bucketname="" \
  -e AWSRegion="ap-south-1" \
  -e dbInstanceIdentifier="RISKDBADCB" \
  -e engine="" \
  -e IsThroughSMTP="N" \
  -e From="utsavsingh085@gmail.com" \
  -e SMTPUsername="utsavsingh085@gmail.com" \
  -e SMTPPassword="pnmhxysmdigqjxyd" \
  -e SMTPHost="smtp.gmail.com" \
  -e SMTPPort="587" \
  -e RealmUrl="https://ec2-13-233-255-125.ap-south-1.compute.amazonaws.com" \
  -e certificatepath="" \
  -e certificatepassword="" \
  -e httpport="" \
  -e httpsport="" \
  -e IsSSOApplicable="Y" \
  -e IsEnvironmentVariableApplicable="Y" \
  fcranew
